import '@testing-library/jest-dom';

// Mock window.api for all renderer tests
const noop = () => () => {}; // returns unsubscribe fn

window.api = {
  getTracks: vi.fn().mockResolvedValue([]),
  getTrackIds: vi.fn().mockResolvedValue([]),
  getCuePoints: vi.fn().mockResolvedValue([]),
  addCuePoint: vi.fn().mockResolvedValue({ id: 1 }),
  updateCuePoint: vi.fn().mockResolvedValue({ ok: true }),
  deleteCuePoint: vi.fn().mockResolvedValue({ ok: true }),
  generateCuePoints: vi.fn().mockResolvedValue([]),
  getPlaylists: vi.fn().mockResolvedValue([]),
  getPlaylist: vi.fn().mockResolvedValue(null),
  createPlaylist: vi.fn().mockResolvedValue({ id: 1 }),
  renamePlaylist: vi.fn().mockResolvedValue(undefined),
  updatePlaylistColor: vi.fn().mockResolvedValue(undefined),
  deletePlaylist: vi.fn().mockResolvedValue(undefined),
  addTracksToPlaylist: vi.fn().mockResolvedValue(undefined),
  removeTrackFromPlaylist: vi.fn().mockResolvedValue(undefined),
  reorderPlaylist: vi.fn().mockResolvedValue(undefined),
  getPlaylistsForTrack: vi.fn().mockResolvedValue([]),
  selectAudioFiles: vi.fn().mockResolvedValue([]),
  importAudioFiles: vi.fn().mockResolvedValue([]),
  reanalyzeTrack: vi.fn().mockResolvedValue({ ok: true }),
  removeTrack: vi.fn().mockResolvedValue({ ok: true }),
  adjustBpm: vi.fn().mockResolvedValue([]),
  updateTrack: vi.fn().mockResolvedValue({}),
  exportPlaylistAsM3U: vi.fn().mockResolvedValue({ canceled: true }),
  getSetting: vi.fn().mockResolvedValue(null),
  setSetting: vi.fn().mockResolvedValue(undefined),
  normalizeLibrary: vi.fn().mockResolvedValue({ normalized: 0, skipped: 0, total: 0 }),
  normalizeTracksAudio: vi.fn().mockResolvedValue({ normalized: 0, skipped: 0 }),
  getNormalizedCount: vi.fn().mockResolvedValue(0),
  getLibraryPath: vi.fn().mockResolvedValue('/tmp/audio'),
  moveLibrary: vi.fn().mockResolvedValue({ moved: 0, total: 0 }),
  openDirDialog: vi.fn().mockResolvedValue(null),
  getDepVersions: vi.fn().mockResolvedValue({}),
  checkDepUpdates: vi.fn().mockResolvedValue({}),
  updateAllDeps: vi.fn().mockResolvedValue(undefined),
  updateTidalDlNg: vi.fn().mockResolvedValue({ ok: true }),
  clearLibrary: vi.fn().mockResolvedValue(undefined),
  clearUserData: vi.fn().mockResolvedValue(undefined),
  getLogDir: vi.fn().mockResolvedValue('/tmp/logs'),
  openLogDir: vi.fn().mockResolvedValue(undefined),
  log: vi.fn(),
  onTrackUpdated: vi.fn().mockImplementation(noop),
  onLibraryUpdated: vi.fn().mockImplementation(noop),
  onPlaylistsUpdated: vi.fn().mockImplementation(noop),
  onOpenSettings: vi.fn().mockImplementation(noop),
  onDepsProgress: vi.fn().mockImplementation(noop),
  onMoveLibraryProgress: vi.fn().mockImplementation(noop),
  onExportM3UProgress: vi.fn().mockImplementation(noop),
  onImportProgress: vi.fn().mockImplementation(noop),
  onNormalizeProgress: vi.fn().mockImplementation(noop),
  getMediaPort: vi.fn().mockResolvedValue(19876),
  ytDlpFetchInfo: vi.fn().mockResolvedValue({ ok: false, error: 'not configured' }),
  checkDuplicateUrls: vi.fn().mockResolvedValue([]),
  getPlaylistSourceUrls: vi.fn().mockResolvedValue([]),
  ytDlpDownloadUrl: vi.fn().mockResolvedValue({ ok: true, trackIds: [] }),
  onYtDlpProgress: vi.fn().mockImplementation(() => () => {}),
  onYtDlpCheckProgress: vi.fn().mockImplementation(() => () => {}),
  onYtDlpEntriesReady: vi.fn().mockImplementation(() => () => {}),
  onYtDlpEntryChecked: vi.fn().mockImplementation(() => () => {}),
  onYtDlpTrackUpdate: vi.fn().mockImplementation(() => () => {}),
  tidalCheck: vi.fn().mockResolvedValue({ installed: false, loggedIn: false, path: null }),
  tidalInstall: vi.fn().mockResolvedValue({ ok: true }),
  tidalFetchInfo: vi.fn().mockResolvedValue({ ok: false, error: 'not configured' }),
  tidalLogin: vi.fn().mockResolvedValue({ ok: true }),
  tidalDownloadUrl: vi.fn().mockResolvedValue({ ok: true, trackIds: [], playlistId: null }),
  onTidalProgress: vi.fn().mockImplementation(() => () => {}),
  onTidalLoginUrl: vi.fn().mockImplementation(() => () => {}),
  onTidalInstallProgress: vi.fn().mockImplementation(() => () => {}),
  onTidalTrackUpdate: vi.fn().mockImplementation(() => () => {}),
  openExternal: vi.fn().mockResolvedValue(undefined),
  checkUsbFormat: vi
    .fn()
    .mockResolvedValue({ needsFormat: false, fs: 'fat32', fsLabel: 'fat32', device: '/dev/sdb1' }),
  formatUsb: vi.fn().mockResolvedValue({ ok: true }),
  exportRekordbox: vi.fn().mockResolvedValue({ ok: true, trackCount: 5, usbRoot: '/tmp/usb' }),
  exportAll: vi
    .fn()
    .mockResolvedValue({ ok: true, trackCount: 5, playlistCount: 2, usbRoot: '/tmp/usb' }),
  onExportRekordboxProgress: vi.fn().mockImplementation(noop),
  onExportAllProgress: vi.fn().mockImplementation(noop),
  onFormatUsbProgress: vi.fn().mockImplementation(noop),
};
